include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Encourage good coding practices
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    avoid_print: true
    use_key_in_widget_constructors: true
    
    # Enforce proper naming
    camel_case_types: true
    library_names: true
    file_names: true
    
    # Security
    avoid_web_libraries_in_flutter: true
    
    # Performance
    prefer_const_declarations: true
    prefer_final_fields: true
    
    # Style
    curly_braces_in_flow_control_structures: true
    prefer_is_empty: true
    prefer_is_not_empty: true